version: '2'
services:
    as2-mysql:
        container_name: as2-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/As2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=as2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
